"""make grid slot order ids unique

Revision ID: d6aa3d3f9521
Revises: a6f2c8d9e1b4
Create Date: 2026-04-26 11:22:44.590644

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6aa3d3f9521"
down_revision: str | Sequence[str] | None = "a6f2c8d9e1b4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_grid_slot_records_buy_order_id"), table_name="grid_slot_records")
    op.create_index("ix_grid_slot_records_buy_order_id", "grid_slot_records", ["buy_order_id"], unique=True)
    op.drop_index(op.f("ix_grid_slot_records_sell_order_id"), table_name="grid_slot_records")
    op.create_index("ix_grid_slot_records_sell_order_id", "grid_slot_records", ["sell_order_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_grid_slot_records_sell_order_id", table_name="grid_slot_records")
    op.create_index(op.f("ix_grid_slot_records_sell_order_id"), "grid_slot_records", ["sell_order_id"], unique=False)
    op.drop_index("ix_grid_slot_records_buy_order_id", table_name="grid_slot_records")
    op.create_index(op.f("ix_grid_slot_records_buy_order_id"), "grid_slot_records", ["buy_order_id"], unique=False)
    # ### end Alembic commands ###
