"""add daily_stats and system_events tables

Revision ID: df98e4f6725a
Revises: e19af1b96316
Create Date: 2026-04-13 10:07:25.004527

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df98e4f6725a"
down_revision: str | Sequence[str] | None = "e19af1b96316"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("daily_stats",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("date", sa.Date(), nullable=False),
    sa.Column("starting_equity", sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column("ending_equity", sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column("total_trades", sa.Integer(), server_default="0", nullable=False),
    sa.Column("winning_trades", sa.Integer(), server_default="0", nullable=False),
    sa.Column("losing_trades", sa.Integer(), server_default="0", nullable=False),
    sa.Column("consecutive_losses", sa.Integer(), server_default="0", nullable=False),
    sa.Column("gross_pnl", sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column("total_fees", sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column("net_pnl", sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column("daily_loss_pct", sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column("circuit_breaker_triggered", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("date"),
    )
    op.create_table("system_events",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("event_type", sa.Enum("KILL_SWITCH", "CIRCUIT_BREAKER", "COOLDOWN", "ERROR", name="systemeventtype", native_enum=False), nullable=True),
    sa.Column("description", sa.Text(), nullable=True),
    sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("system_events")
    op.drop_table("daily_stats")
    # ### end Alembic commands ###
