"""add signals and trades tables

Revision ID: e19af1b96316
Revises:
Create Date: 2026-04-13 09:50:43.637358

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e19af1b96316"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("signals",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("symbol", sa.String(length=20), nullable=False),
    sa.Column("signal_direction", sa.Enum("LONG", "SHORT", name="signaldirection", native_enum=False), nullable=False),
    sa.Column("reason", sa.Text(), nullable=True),
    sa.Column("strategy_version", sa.String(length=20), nullable=True),
    sa.Column("indicators_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    )
    op.create_table("trades",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("signal_id", sa.UUID(), nullable=True),
    sa.Column("order_link_id", sa.String(length=64), nullable=True),
    sa.Column("exchange_order_id", sa.String(length=64), nullable=True),
    sa.Column("symbol", sa.String(length=20), nullable=False),
    sa.Column("signal_direction", sa.Enum("LONG", "SHORT", name="signaldirection", native_enum=False), nullable=False),
    sa.Column("exchange_side", sa.Enum("BUY", "SELL", name="exchangeside", native_enum=False), nullable=False),
    sa.Column("market_type", sa.Enum("SPOT", "SPOT_MARGIN", "LINEAR", name="markettype", native_enum=False), nullable=False),
    sa.Column("mode", sa.Enum("SHADOW", "DEMO", "REAL", name="tradingmode", native_enum=False), nullable=False),
    sa.Column("equity_at_entry", sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column("risk_amount_usd", sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column("risk_pct", sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column("entry_price", sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column("stop_price", sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column("target_price", sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column("expected_rrr", sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column("qty", sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column("order_type", sa.String(length=20), nullable=True),
    sa.Column("is_post_only", sa.Boolean(), nullable=False),
    sa.Column("is_reduce_only", sa.Boolean(), nullable=False),
    sa.Column("avg_fill_price", sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column("filled_qty", sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column("fee_paid", sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column("slippage", sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column("status", sa.Enum("SIGNAL_GENERATED", "RISK_CALCULATED", "SAFETY_CHECKED", "ORDER_SUBMITTED", "ORDER_CONFIRMED", "ORDER_REJECTED", "ORDER_CANCELLED", "ORDER_PARTIALLY_FILLED", "POSITION_OPEN", "POSITION_CLOSE_PENDING", "POSITION_CLOSED", "POSITION_CLOSE_FAILED", "PNL_RECORDED", name="tradestatus", native_enum=False), nullable=False),
    sa.Column("exit_reason", sa.Enum("TP_HIT", "SL_HIT", "MANUAL", "KILL_SWITCH", name="exitreason", native_enum=False), nullable=True),
    sa.Column("realized_pnl", sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column("pnl_pct", sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column("pnl_in_r", sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column("mae", sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column("mfe", sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column("hold_time_seconds", sa.Integer(), nullable=True),
    sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["signal_id"], ["signals.id"] ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("order_link_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trades")
    op.drop_table("signals")
    # ### end Alembic commands ###
